Repository hudson-and-thames/research, pull requests merged in 2020-06, with the labels that each got.

#160 Update fixed horizon notebook to reflect changes in the method
  Labelling/Labels Fixed Horizon/Fixed Time Horizon.ipynb
Labels: Documentation

#157 Labeling vs benchmark
  Labelling/Labeling vs Benchmark/Labeling vs Benchmark.ipynb
  Labelling/Labeling vs Benchmark/img/MSFT_Return_vs_Benchmark.png
Labels: Documentation

#152 Add notebook with examples for Codepencence by Marti
  Codependence/Codependence by Marti/codependence_by_marti.ipynb
Labels: Research

#169 OLPS tuning script
  Online Portfolio Selection/olps_create_obj.py
  Online Portfolio Selection/olps_tuning.py
Labels: enhancement

#167 Labeling matrix flag
  Labelling/Labels Matrix Flags/Matrix Flag Labels.ipynb
  Labelling/Labels Matrix Flags/img/bull_flag_template.png
  Labelling/Labels Matrix Flags/img/msft_bull_flag40.png
Labels: Documentation

#168 Notebook for labeling over mean
  Labelling/Labels Excess Over Mean/excess_over_mean.ipynb
  Labelling/Labels Excess Over Mean/img/distribution_over_mean.png
Labels: Documentation

#173 Fix MlFinLab issues
  Advances in Financial Machine Learning/Fractionally Differentiated Features/Chapter5_Exercises.ipynb
Labels: Documentation

#172 RiskEstimators notebook updated
  Portfolio Optimisation Tutorials/Risk Estimators/RiskEstimators.ipynb
Labels: Documentation, enhancement
