Repository hudson-and-thames/research, pull requests merged in 2020-05, with the labels that each got.

#129 Create Data Selection.ipynb
  .gitignore
  Online Portfolio Selection/Data Selection.ipynb
Labels: Research

#130 exponential gradient first draft
  Online Portfolio Selection/Online Portfolio Selection - Momentum - Exponential Gradient.ipynb
Labels: Research

#132 Finished FTRL trials
  .gitignore
  Online Portfolio Selection/Online Portfolio Selection - Momentum.ipynb
Labels: enhancement

#123 Create HRP use examples.ipynb
  HRP/HRP use examples.ipynb
Labels: Research

#145 Labeling excess median
  Labelling/Labels Excess Over Median/Excess over Median.ipynb
  Labelling/Labels Excess Over Median/img/distribution_over_median.png
Labels: Documentation
